# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

r_binary_packages:
 - testthat

before_script: "Rscript ./travis_prep.R"

script: ./travis_run_build.sh

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev
